"""Initial database schema

Revision ID: 17da95107fcd
Revises: 
Create Date: 2025-05-10 16:46:19.473053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17da95107fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('analysis_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('overall_sentiment_label', sa.String(length=64), nullable=True),
    sa.Column('overall_sentiment_score', sa.Float(), nullable=True),
    sa.Column('aggregated_intents_json', sa.Text(), nullable=True),
    sa.Column('aggregated_keywords_json', sa.Text(), nullable=True),
    sa.Column('sentiment_trend_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_report_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_report_shares',
    sa.Column('analysis_report_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_report_id'], ['analysis_report.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('analysis_report_id', 'recipient_id')
    )
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=64), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intents', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('analysis_report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_report_id'], ['analysis_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_item_analysis_report_id'), ['analysis_report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_item_analysis_report_id'))

    op.drop_table('news_item')
    op.drop_table('analysis_report_shares')
    with op.batch_alter_table('analysis_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_report_user_id'))

    op.drop_table('analysis_report')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
