"""Add summary field to NewsItem model

Revision ID: 5c55d4999ffe
Revises: 17da95107fcd
Create Date: 2025-05-16 00:01:14.558751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c55d4999ffe'
down_revision = '17da95107fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
