"""Add summary column to news_item and analysis_report

Revision ID: 9036e2575233
Revises: 5c55d4999ffe
Create Date: 2025-05-16 00:23:04.180156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9036e2575233'
down_revision = '5c55d4999ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_report', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
